[Fix] Deployment failed due to following
```
ERROR: failed to calculate checksum of ref rd0fccwmxizxklor3ogi0gta2::qoar407w3scjq4ireh111o2mv: failed to walk /home/user/.local/tmp/buildkit-mount2539495225/build/libs: lstat /home/user/.local/tmp/buildkit-mount2539495225/build/libs: no such file or directory
```